version: '2'

services:
  # sets up to build backend and frontend 
  backend:
    build:
      context: './BackEnd'
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
  frontend:
    build:
      context: './FrontEnd/myapp'
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    # connects frontend to backend 
    links:
      - "backend"
    tty: true
    stdin_open: true
    
