version: '2'

services:
  backend:
    build:
      context: './BackEnd'
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
  frontend:
    build:
      context: './frontend/myapp'
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    
