version: 2
jobs:
  build:
    working_directory: ~/majorproject-7-tues-14-30-2/BackEnd
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout:
        path: ~/majorproject-7-tues-14-30-2
      
      - run: pwd
      
      - run: ls
      
      - run: readlink -f pom.xml | xargs dirname

      - restore_cache:
          key: BackEnd-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: BackEnd-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/majorproject-0.0.1-SNAPSHOT.jar